/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bot_Decompress */

#ifndef _Included_bot_Decompress
#define _Included_bot_Decompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bot_Decompress
 * Method:    bytes
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bot_Decompress_bytes
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
